/* uslugi fryzjerskie */
INSERT INTO `SalonikBella`.`haircut` (`description`,`duration`,`gender`,`max_price`,`name`, `price`) VALUES ('strzyżenie męskie',20,0,0,'strzyżenie męskie',25);
INSERT INTO `SalonikBella`.`haircut` (`description`,`duration`,`gender`,`max_price`,`name`, `price`) VALUES ('strzyżenie dzieci',20,2,30,'strzyżenie dzieci',25);
INSERT INTO `SalonikBella`.`haircut` (`description`,`duration`,`gender`,`max_price`,`name`, `price`) VALUES ('Strzyżenie damskie z modelowaniem',45,1,50,'Strzyżenie damskie z modelowaniem',40);
INSERT INTO `SalonikBella`.`haircut` (`description`,`duration`,`gender`,`max_price`,`name`, `price`) VALUES ('Koloryzacja odrostów',90,1,0,'Koloryzacja odrostów',100);
INSERT INTO `SalonikBella`.`haircut` (`description`,`duration`,`gender`,`max_price`,`name`, `price`) VALUES ('Pasemka, ombre',180,1,160,'Pasemka, ombre',110);
INSERT INTO `SalonikBella`.`haircut` (`description`,`duration`,`gender`,`max_price`,`name`, `price`) VALUES ('Fryzury okolicznościowe',60,1,130,'Fryzury okolicznościowe',40);
INSERT INTO `SalonikBella`.`haircut` (`description`,`duration`,`gender`,`max_price`,`name`, `price`) VALUES ('Styling (trwała)',120,1,0,'Styling (trwała)',100);
INSERT INTO `SalonikBella`.`haircut` (`description`,`duration`,`gender`,`max_price`,`name`, `price`) VALUES ('Keratynowe prostowanie włosów',180,1,350,'Keratynowe prostowanie włosów',250);
INSERT INTO `SalonikBella`.`haircut` (`description`,`duration`,`gender`,`max_price`,`name`, `price`) VALUES ('Nawilżanie włosów',45,1,0,'Nawilżanie włosów',60);

/* perfumy 15 ml */
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Eksplozja nut cytrusowych tworzy bardzo pociągający zapach. Delikatne akordy piżma napawają  pogodnym nastawieniem.','BRAK','m','beach','img/perfumy/beach/beach15.jpg',25,'Aromatyczno - Drzewna, Beach to zrównoważony, czysty zapach. Idealny dla kobiet i mężczyzn. Nuty głowy: Pomarańcza, nuty serca: Konwalia, nuty bazy: Piżmo.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Fuzja nut hesperydowych z cyklamenem i nutami drzewnymi pozwoliła na stworzenie ekspresywnego zapachu pachnącego wolnością.','BRAK','m','acqua per uomo','img/perfumy/acqua-per-uomo/acqua-per-uomo15.jpg',25,'Aromatyczno - Wodna. Acqua per uomo to świeży zapach dla naturalnego i współczesnego mężczyzny. Nuty głowy: Bergamotka, nuty serca  Cyklamen, nuty bazy: Drzewo.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Te perfumy pełne aromatycznych nut nadają mężczyźnie, który ich używa uwodzicielskiego i prawdziwie męskiego charakteru.','BRAK','m','wow scent!','img/perfumy/wow-scent/wow-scent15.jpg',25,'Paprociowo – Korzenny. Wow Scent! to męskie perfumy dla żywiołowego I radosnego mężczyzny. Nuty głowy: Mięta, nuty serca: Szałwia, nuty bazy: Wanilia','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Uwodzicielska i intensywna kompozycja zapachowa będąca połączeniem pogodnej maliny z miękką gardenią i ciepłem paczuli.','BRAK','k','power woman','img/perfumy/power-woman/power-woman15.jpg',25,'Power Woman to zapach pełen oryginalnych kontrastów. Dla ambitnej kobiety z charakterem. Nuty głowy: Malina, nuty serca: Gardenia, nuty bazy: Paczuli.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Odczuwalna świeżość mandarynki w połączeniu z esencjami gardenią i drzewa sandałowego tworzy wyjątkowo wyrafinowany zapach.','BRAK','k','notion woman','img/perfumy/notion-woman/notion-woman15.jpg',25,'Kwiatowo - Owocowa. Notion Woman to zapach dla wesołej, dynamicznej kobiety, emanującej optymizmem i elegancją. Nuty głowy: Mandarynka, nuty serca: Gardenia, nuty bazy: Sandał.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Mocno pudrowy aromat białych kwiatów, orientalne tło i ciepło kwiatowego bukietu odzwierciedlają zmysłowość i delikatność. ','BRAK','k','velfashion','img/perfumy/velfashion/velfashion15.jpg',25,'Orientalno - Waniliowa. Velfashion  to złożony i elegancki zapach. Dla kobiety z wdziękiem i charyzmą. Nuty głowy: Bergamotka, nuty serca: Jaśmin, nuty bazy: Wetiweria pachnąca.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Uwodzicielska fuzja cytryny, imbiru i kardamonu daje w efekcie pocigąjący i niezapomniany zapach','BRAK','m','west','img/perfumy/west/west15.jpg',25,'Szyprowo-Drzewna. West to perfumy dla odważnego i charyzmatycznego mężczyzny. Nuty głowy: Cytryna, nuty serca: Kardamon, nuty bazy: Bób tonka','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Silne nuty bergamotki i lawendy nadają kompozycji klasyczny męski charakter, które łagodzi delikatny aromat ambry.','BRAK','m','CARIBBEAN','img/perfumy/caribbean/caribbean15.jpg',25,'Paprociowo - Ambrowa. Caribbean jest to świeży zapach dla prawdziwego i przebojowego mężczyzny. Nuty głowy: Bergamotka, nuty serca: Lavenda, nuty bazy: Bursztyn','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Charakterystyczna piramida zapachowa, w której dominują nuty orientalne, tworzy zapach emanujący siłą i trwałością.','BRAK','m','INSTINT','img/perfumy/instint/instint15.jpg',25,'Orientalno - Korzenna. Instint to zapach wyjątkowo prowokacyjny. Dla odważnego i seksownego mężczyzny. Nuty głowy: Kwiat pomarńczy, nuty serca: Lavenda, nuty bazy: Wanilia.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Orzeźwiający i zmysłowy zapach wykreowany dzięki połączeniu energicznych i intensywnych nut drzewnych ze słodyczą jaśminu.','BRAK','m','platinum','img/perfumy/platinum/platinum15.jpg',25,'Drzewno - wodna. Platinum  to zapach pełen mocy. Dla aktywnego, uwielbiającego przygody mężczyzny. Nuty głowy: Grejpfrut, nuty serca: Jaśmin, nuty bazy: Drzewo.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Owocowe nuty głowy ustępują ciepłym nutom drzewnym kreując wyrafinowany i elegancki zapach.','BRAK','m','MOMENT','img/perfumy/moment/moment15.jpg',25,'Orientalno - drzewna. Moment to elegancki, czysty zapach. Dla mężczyzny pewnego siebie. Nuty głowy: Jabłko, nuty serca: Cynamon, nuty bazy: Drzewo.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Nowoczesne połączenie swieżych i iskrzących akordów zapewniają temu zapachowi zmysłowość, wyrazistość i osobowość.','BRAK','m','metal sport','img/perfumy/metal-sport/metal-sport15.jpg',25,'Szyprowo - Owocowa. Metal Sport to zapach dla atrakcyjnego, uwodzicielskiego i energicznego mężczyzny. Nuty głowy: Mandarynka, nuty serca: Drzewo, nuty bazy: Wetiweria pachnąca.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Otulający aromat piżma i elegancja białej róży kształtuje perfumy o namiętnej zmysłowości.','BRAK','k','nicolas white','img/perfumy/nicolas-white/nicolas-white15.jpg',25,'Kwiatowo-Drzewna. Nicolás White jest to piżmowo- kwiatowy zapach dla bardzo zmysłowej kobiety. Nuty głowy: Biała róża, nuty serca : Piżmo, nuty bazy: Biały cedr.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Owocowe i aksamitne nuty granatu, wraz z  czarującą wonią orchidei i fiołka, tworzą odważny i wykwintny zapach.','BRAK','k','aroma','img/perfumy/aroma/aroma15.jpg',25,'Orientalno - Kwiatowa. Aroma to  egzotyczny i nadający blask zapach. Dla eleganckiej i tajemniczej kobiety. Nuty głowy: Granat, nuty serca: Orchidea, nuty bazy: Fiołek.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Nowoczesna kompozycja aromatyczna tworzy odważny zapach, odzwierciedlający luksus i elegancję.','BRAK','k','cheante','img/perfumy/cheante/cheante15.jpg',25,'Szyprowo - Kwiatowa. Cheante to  kobiecy i zmysłowy zapach. Dla eleganckiej i szykownej kobiety. Nuty głowy: Bergamotka, nuty serca: Róża, nuty bazy: Piżmo.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Współczesna i luksusowa kompozycja zapachowa powstała z połączenia wibrujących nut głowy z namiętną fuzją  jaśminu i wetywerii.','BRAK','k','sophiesticate','img/perfumy/sophiesticate/sophiesticate15.jpg',25,'Orientalno - Kwiatowa. Sophisticate to zmysłowy zapach. Dla namiętnej i silnej kobiety. Nuty głowy: Liczi, nuty serca: Jaśmin, nuty bazy: Wetiweria pachnąca.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Pociągające słodkie nuty czarnej porzeczki i silna obecność wanilii sprawiają, iż od samego początku perfumy posiadają własną osobowość.','BRAK','k','adriana','img/perfumy/adriana/adriana15.jpg',25,'Szyprowo - Owocowa. Pociągające słodkie nuty czarnej porzeczki i silna obecność wanilii sprawiają, iż od samego początku perfumy posiadają własną osobowość. Nuty głowy: Czarna porzeczka,nuty serca: Wanilia, nuty bazy: Drzewo.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Świeżość bergamotki i elegancja róży z dodatkiem waniliowej głębi tych perfum, nadają im ponadczasowy i nowoczesny charakter.','BRAK','k','adriana rose','img/perfumy/adriana-rose/adriana-rose15.jpg',25,'Chypre Fruity. Jest to elegancki i niepowtarzalnie kobiecy zapach. Nuty głowy: Bergamotka, nuty serca: Róża, nuty bazy: Wanilia.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Świeżość grejpfruta, delikatność jaśminu oraz poetyckie połączenie ambry tworzy perfumy słodkie i cytrusowe.','BRAK','k','for you','img/perfumy/for-you/for-you15.jpg',25,'Kwiatowo-Owocowy. For You są to subtelne i delikatne perfumy dla optymistycznej kobiety. Nuty głowy: Bergamotka, Grejpfrut, nuty serca: Jaśmin, nuty bazy: Bursztyn, Biały cedr.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Zmysłowy zapach będący połączeniem delikatnego jabłka i bambusu, które nadają świeżych akrodów nutą drzewnym.','BRAK','k','kara','img/perfumy/kara/kara15.jpg',25,'Kwiatowo - Owocowa. Kara to pobudzający zapach. Dla radosnej, cieszącej się życiem kobiety. Nuty głowy: Jabłko, nuty serca: Bambus, nuty bazy: Piżmo.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Intensywne połączenie białych kwiatów i bobu tonka tworzy odważne i wyszukane perfumy.','BRAK','k','very special','img/perfumy/very-special/very-special15.jpg',25,'Orientalno - Kwiatowa. Very Special to perfumy dla wpływowej i namiętnej kobiety. Nuty głowy: Tuberoza, Migdały, nuty serca: Jaśmin, nuty bazy: Bób tonka.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Zapach otulony miękkością i czułością dzięki harmonijnemu połączeniu nut zapachowych. Jego pudrowe nuty upajają marzeniami.','BRAK','k','seduccion','img/perfumy/seduccion/seduccion15.jpg',25,'Kwiatowo - Kwiatowa. Seducción to słodki, ujmujący zapach. Dla wyjątkowej i delikatnej kobiety. Nuty głowy: Piwonia, nuty serca: Konwalia, nuty bazy: Piżmo.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Kwiatowa etuida wraz z nutami wanilii tworzy niezapomniany zapach pudrowy. Delikatny a zarazem silny i wyjątkowy aromat rozbudza niezliczone doznania.','BRAK','k','berlue','img/perfumy/berlue/berlue15.jpg',25,'Kwiatowo - Aldehydowa. Berlue to  ponadczasowy zapach. Dla kobiety uwielbiającej klasyczny i elegancki styl. Nuty głowy: Kwiat pomarńczy, nuty serca: Róża, nuty bazy: Wanilia.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Dominujący zapach wanilii sprawia, że zapach ten jest urzekający i charyzmatyczny. ','BRAK','k','temis','img/perfumy/temis/temis15.jpg',25,'Orientalno - Kwiatowa. Temis to perfumy dla kobiety tajemniczej i prowokującej. Nuty głowy: Kwiat Imbiru, nuty serca: Jaśmin Wodny, nuty bazy: Wanilia.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Zapach elegancki i zmysłowy, powstały z kreatywnego połączenia nut cytrusowych z cynamonem i świeżą paczulą.','BRAK','m','power','img/perfumy/power/power15.jpg',25,'Power to intesywny, pobudzający zapach. Dla uwodzicielskiego, tajemniczego mężczyzny. Nuty głowy: Grejpfrut, nuty serca: Cynamon, nuty bazy: Paczuli.','15');

/* perfumy 50 ml */
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Zapach elegancki i zmysłowy, powstały z kreatywnego połączenia nut cytrusowych z cynamonem i świeżą paczulą.','BRAK','m','power','img/perfumy/power/power50.jpg',60,'Power to intesywny, pobudzający zapach. Dla uwodzicielskiego, tajemniczego mężczyzny. Nuty głowy: Grejpfrut, nuty serca: Cynamon, nuty bazy: Paczuli.','50');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Żywe cytrusowe nuty harmonijnie otaczają spokojny aromat róży, nadając życiu radosny i delikatny zapach.','BRAK','k','vivacity','img/perfumy/vivacity/vivacity50.jpg',60,'Vivacity  to zapach dla żywiołowej i słodkiej kobiety. Nuty głowy: Mandarynka, nuty serca: Róża Grasse, nuty bazy: Drzewo sandałowe.','50');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Świeżość bergamotki i imbiru kontrastuje z zapachem jabłka, a nuty szałwii, jałowca i lawendy gwarantują zapach silnej męskości.','BRAK','m','resolu','img/perfumy/resolu/resolu50.jpg',60,'Reslou dla energicznego i wytrwałego mężczyzny. Nuty głowy: Bergamotka, Jabłko, Imbir, nuty serca: Jałowieć, Lawenda, Szałwia , nuty bazy: Drewno bursztynowe, Olibanum, Fasolka tonka.','50');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Intensywność bergamotki i kakao sprawiają, że te perfumy są niezapomnianym przeżyciem, które sprawi, że przemierzysz cały świat.','BRAK','m','peak','img/perfumy/peak/peak50.jpg',60,'Peak dla mężczyzny pełnego życia z charakterem. Nuty głowy: Bergamotka, nuty serca: Skóra, nuty bazy: Kakao.','50');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Cytrusowy dotyk bergamotki wraz z urzekającymi nutami tuberozy i paczuli tworzą intensywny i kobiecy zapach.','BRAK','k','tendenze','img/perfumy/tendenze/tendenze50.jpg',60,'Tendenze to mocny cytrusowo kwiatowy zapach. Idealny dla eleganckiej i odważnej kobiety. Nuty głowy: Bergamotka, nuty serca: Tuberoza, nuty bazy: Paczula.','50');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Zmysłowość nut zapachowych, które tworzą te perfumy sprawia, że kobieta, która ich używa jest namiętna i nie można się jej oprzeć.','BRAK','k','suerte','img/perfumy/suerte/suerte50.jpg',60,'Suerte to  zapach dla uwodzicielskiej i uroczej kobiety. Nuty głowy: Ylang-ylang, nuty serca: Wanilia, nuty bazy: Białe Piżmo.','50');

/* perfumy 100 ml */
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Owocowe i aksamitne nuty granatu, wraz z  czarującą wonią orchidei i fiołka, tworzą odważny i wykwintny zapach.','BRAK','k','aroma','img/perfumy/aroma/aroma100.jpg',100,'Orientalno - Kwiatowa. Aroma to  egzotyczny i nadający blask zapach. Dla eleganckiej i tajemniczej kobiety. Nuty głowy: Granat, nuty serca: Orchidea, nuty bazy: Fiołek.','100');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Odczuwalna świeżość mandarynki w połączeniu z esencjami gardenią i drzewa sandałowego tworzy wyjątkowo wyrafinowany zapach.','BRAK','k','notion woman','img/perfumy/notion-woman/notion-woman100.jpg',100,'Kwiatowo - Owocowa. Notion Woman to zapach dla wesołej, dynamicznej kobiety, emanującej optymizmem i elegancją. Nuty głowy: Mandarynka, nuty serca: Gardenia, nuty bazy: Sandał.','100');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Uwodzicielska i intensywna kompozycja zapachowa będąca połączeniem pogodnej maliny z miękką gardenią i ciepłem paczuli.','BRAK','k','power woman','img/perfumy/power-woman/power-woman100.jpg',100,'Power Woman to zapach pełen oryginalnych kontrastów. Dla ambitnej kobiety z charakterem. Nuty głowy: Malina, nuty serca: Gardenia, nuty bazy: Paczuli.','100');

/* pictures */
INSERT INTO `SalonikBella`.`picture` (`description`,`name`,`path`,`title`) VALUES ('','','img/galeria/picture1.jpg','');
INSERT INTO `SalonikBella`.`picture` (`description`,`name`,`path`,`title`) VALUES ('','','img/galeria/picture2.jpg','');
INSERT INTO `SalonikBella`.`picture` (`description`,`name`,`path`,`title`) VALUES ('','','img/galeria/picture3.jpg','');
INSERT INTO `SalonikBella`.`picture` (`description`,`name`,`path`,`title`) VALUES ('','','img/galeria/picture4.jpg','');
INSERT INTO `SalonikBella`.`picture` (`description`,`name`,`path`,`title`) VALUES ('','','img/galeria/picture5.jpg','');
INSERT INTO `SalonikBella`.`picture` (`description`,`name`,`path`,`title`) VALUES ('','','img/galeria/picture6.jpg','');
INSERT INTO `SalonikBella`.`picture` (`description`,`name`,`path`,`title`) VALUES ('','','img/galeria/picture7.jpg','');
INSERT INTO `SalonikBella`.`picture` (`description`,`name`,`path`,`title`) VALUES ('','','img/galeria/picture8.jpg','')
INSERT INTO `SalonikBella`.`picture` (`description`,`name`,`path`,`title`) VALUES ('','','img/galeria/picture9.jpg','');
INSERT INTO `SalonikBella`.`picture` (`description`,`name`,`path`,`title`) VALUES ('','','img/galeria/picture10.jpg','');
    /* INSERT INTO `SalonikBella`.`picture` (`description`,`name`,`path`,`title`) VALUES ('','','','');*/

/* products */
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`) VALUES ('Odżywka 3 System to unikalna formuła (bez spłukiwania) zawierająca pantenol, glikol propylenowy, ceramidy, aminokwasy jedwabiu oraz kompleks wyselekcjonowanych polimerów i składników kondycjonujących.','Ta bogata, starannie skomponowana receptura zapewnia aż 15 imponujących efektów: nawilża, wypełnia strukturę włókna włosa, redukując jego porowatość, wzmacnia spoiwo międzykomórkowe włosów, zapobiega puszeniu się włosów, wygładza, ułatwia rozczesywanie, ułatwia prostowanie, nadaje połysk, zapobiega rozdwajaniu końcówek, odżywia włosy, zmiękcza, sprawia, że włosy stają się bardziej sypkie, uelastycznia włókno włosa, redukuje skłonność do łamania się włosów, zapobiega elektryzowaniu.','km','Odżywka 3 system EssentialSalon','img/produkty/profis-3-spectacular-essentialsalon.png',25,'EssentialSalon','250ml');
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`) VALUES ('Mgiełka Podnosząca Włosy u nasady ProSalon Intensis Hair Booster Mist.','Przeznaczona do włosów cienkich i delikatnych. Dzięki zastosowaniu innowacyjnych składników aktywnych zapewnia uzyskanie efektu zwiększonej objętości włosów. Wzmacnia i unosi włosy u nasady, dzięki czemu fryzura zyskuje lekkość i puszystość. Obecne w preparacie proteiny pszenicy pomagają utrzymać prawidłowy poziom nawilżenia, przez co włosy stają się gładkie i  błyszczące. Filtr UV chroni włosy przed działaniem szkodliwych zewnętrznych czynników.','km','Mgiełka Podnosząca Włosy Intensis','img/produkty/prosalon-intensis.png',30,'Chantal','200g');
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`) VALUES ('Spray do nabłyszczenia Schwarzkopf Professional Osis+ Sparkler Finish delikatnie utrwali twoją fryzurę i nada jej olśniewającego blasku.','Właściwości: utrwala fryzurę, przynosi wykończenie pełne blasku, pomaga stworzyć wymarzoną fryzurę','km','Osis+ Sparkler Finish Schwarzkopf','img/produkty/osis-sparkler.png',38,'SchwarzkopfProfessional','300ml');
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`) VALUES ('Zapewnia intensywne i niezrównane utrwalenie.','Utrzymuje fryzurę w mokrych warunkach. Można go łatwo usunąć za pomocą lekkiego szczotkowania.','km','Spray do włosów GODET Yodeyma','img/produkty/yodeyma-godet.png',26,'Yodeyma','300ml');
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`) VALUES ('Guma do stylizacji OSiS Thrill posiada mocną, elastyczną, włóknistą strukturę, która bardzo mocno utrwala stylizowaną fryzurę. Nadaje wysoki połysk i gwarantuje bardzo dobrą separację pojedynczych pasm.','Pozwala na modelowanie włosów, nie obciążając ich nadmiernie. Skutecznie utrzymuje pożądany kształt fryzury i nadaje pasmom naturalny połysk. Swarzkopf OSiS+ thrill to łatwe układanie włosów krótkich i średniej długości. Można go stosować na suche lub lekko wilgotne włosy.','m','Osis+ Thrill Guma do stylizacji','img/produkty/osis-hairgum.png',33,'SchwarzkopfProfessional','100ml');
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`) VALUES ('Argan Oil Gold Serum do włosów z olejkiem arganowym','Lekka odżywka znakomita do pielęgnacji wszystkich rodzajów włosów, a w szczególności do włosów zniszczonych, suchych i szorstkich. Formuła odżywki jest oparta na olejku arganowym, który doskonale odżywia włosy, przywraca im zdrowy wygląd, gładkość i połysk. Odżywka szybko się wchłania, ułatwia rozczesywanie. Nie obciąża włosów.','km','Odżywka do włosów Argan Oil','img/produkty/arganoil-prosalon.png',28,'ProSalon','100ml');
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`) VALUES ('Maska zakwaszająca do włosów Stapiz Acid balance, to profesjonalny produkt o nowoczesnym działaniu, zapewniający prawdziwą głębię koloru','Unikalna formuła o kwaśnym pH pomaga utrzymać włosy farbowane w nieskazitelnej kondycji, a do tego dzięki zawartości filtrów UV chroni jest przed blaknięciem pod wpływem słońca. Za ochronę nowego odcienia i jego wieczny blask odpowiada miks wyciągów z cytrusów i winogron. Towarzyszą im odżywcze proteiny jedwabiu które wnikają w głąb włókien i zapobiegają ich łamaniu się i kruszeniu.','km','Stapiz Acid balance Maska Zakwaszająca Do Włosów','img/produkty/snapiz-acid-balance.png',21,'Stapiz','500ml');
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`) VALUES ('Pianka do układania włosów z ceramidami eliminuje elektryzowanie się włosów, zwiększa objętość, nadaje połysk i zapewnia długotrwałe utrwalenie fryzury.','Dzięki swojemu składowi regeneruje i zabezpiecza włosy przed czynnikami zewnętrznymi takimi jak słońce, wiatr, słona woda.','km','Pianka do włosów Black Equal Strong','img/produkty/blackprofessional-mousse-ristrutturante.png',25,'Black','400ml');
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`) VALUES ('Lakier do włosów ekstra strong z pantenolem. Jego formuła nadaje włosom nową siłę oraz zapewnia pełne nawilżenie, przywracając włosom fizjologiczną równowagę.','Zapewnia  lekką stylizację, nadając  połysk i objetość o długotrwałym efekcie. Nie moczy włosów, nie działa na ich strukturę, wzmacniając je bez wpływania na ich naturalną elastyczność. Lakier ten chroni przed szkodliwym wpływem wilgoci i czynników atmosferycznych. Nie zostawia po sobie śladów.','km','Lakier do włosów Lacca','img/produkty/allwaves-laccaspray.png',25,'Allwaves','750ml');
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`) VALUES ('Chantal intensis voluming powder to puder zwiększający objętość włosów','Stworzony z myślą o pielęgnacji włosów cienkich, płaskich i wiotkich. Nadaje natychmiastową objętość włosom bez ich obciążania. Unosi włosy u nasady, dzięki czemu fryzura zyskuje naturalną lekkość i puszystość. Specjalnie opracowana formuła absorbuje nadmiar sebum, przywracając świeży wygląd włosom przetłuszczonym i obciążonym. Puder nie skleja włosów, nadaje efekt matowego wykończenia.','k','Puder zwiększający objętość włosów Intensis','img/produkty/voluming-powder-intensis.png',20,'ProSalon','20g');
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`) VALUES ('Schwarzkopf bc Q10 night to odżywczy spray na noc do włosów dojrzałych','Głęboko odżywiająca, intensywna maseczka na noc, o kremowej konsystencji w sprayu. Tzw. Zawiera koenzym Q10, który wzmacnia osłabione i podatne na łamanie i wypadanie włosy. Nadaje im intensywny połysk i gładkość. Wspomaga wzrost zdrowych włosów. Zawarty w składzie koenzym Q10 reaktywuje proces produkcji keratyny, który wraz z upływem czasu ulega spowolnieniu.','km','Spray odżywczy Schwarzkopf Q10 Night','img/produkty/q10-night-spray.png',16,'SchwarzkopfProfessional','100ml');
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`) VALUES ('O’revle bioceana elixir, to odżywka dwufazowa o ekspresowym działaniu, która polecana jest do włosów zniszczonych, przetłuszczających się, oraz trudnych do rozczesania.','Twoje włosy stają się odżywione, wygładzone i doskonale nawilżone. Formuła elixiru rozświetla i zapewnia ochronę przed wysokimi temperaturami oraz nadmiernym wysuszeniem podczas stylizacji. Włosy doskonale się rozczesują i mniej przetłuszczają, zachowując lekkość i sprężystość.','km','Odżywka dwufazowa O’revle bioceana','img/produkty/odzywka-biocena.png',25,'Scandic','250ml');
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`) VALUES ('Maska do włosów Stapiz Ha Essence pozwala zregenerować, odbudować oraz właściwie nawilżyć swoje suche i zniszczone włosy.','zawiera kwas hialuronowy i algi, znane z doskonałego działania nawilżającego, dzięki czemu maska Ha Essence przywraca włosom odpowiedni poziom wilgoci. Algi w zawarte w formule kosmetyku zaopatrują też włosy w aminokwasy, składniki mineralne oraz proteiny. Pasma stają się sprężyste, miękkie i gładkie w dotyku. Odżywka Stapiz ułatwia również rozczesywanie włosów, co sprawia, że codzienna pielęgnacja staje się przyjemnością.','km','Maska do włosów Ha Essence','img/produkty/maska-ha-essence.png',30,'Stapiz','1000ml');
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`) VALUES ('Szampon Londa Professional Impressive Volume skutecznie oczyszcza skórę głowy, dokładnie myje włosy i przywraca im naturalne piękno zwiększając jego objętość','Szampon gwarantuje, że włosy będą uniesione od nasady i będą wyglądać na zdecydowanie gęstsze i grubsze. Formuła mikro-perełkowa z wyciągiem kwiatu lotosu nadaje włosom objętość, elastyczność i połysk. Dzięki trawie cytrynowej i ekstrakcie z bambusa włosy wyglądają na pełne objętości, lekkie i pełne blasku.','km','Szampon Londa Impressive Volume','img/produkty/szampon-londa-impresive-volume.png',44,'Londa','1000ml');
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`) VALUES ('Szampon Londa Deep Moisture zaleca się dla włosów nadmiernie przesuszonych. Dzięki specjalnym składników i formule Radialux Micro-Ionic do włosów zostaną dostarczone substancje odżywcze oraz nawilżające. Sprawi to, że włosy odzyskają miękkość oraz zostaną głęboko nawilżone.','Szampon Londa Deep Moisture został wyposażony w specjalne składniki, takie jak Radialux Micro-Ionic, który zabezpiecza włosy przed suchością, nawilża i chroni przez negatywnym wpływem czynników zewnętrznych. Kosmetyk posiada silne właściwości oczyszczające, dokładnie usuwa wszelkie pozostałości środków do stylizacji i zanieczyszczenia środowiskowe. Tak jak cała seria, produkt zawiera ekstrakty z mango i miodu. Miód ma działanie antyseptyczne, kojące i pielęgnacyjne. Nastomiast mango ma właściowści gojące.','km','Szampon Londa Deep Moisture','img/produkty/szampon-londa-deep-moisture.png',44,'Londa','1000ml');
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`) VALUES ('Szampon Londa Visible Repair regeneruje i odżywia włosy zniszczone w wyniku chemii fryzjerskiej, trwałej ondulacji i farbowania.','Najważniejszą cechą kosmetyku jest Radialux Micro-Ions, składnik ten nadaje włosom niezwykłą gładkość, jednolitą strukturę oraz piękny połysk. Działanie mikrojonów polega na tym, że wędrują one od razu do uszkodzonych miejsc, tam naprawiają je i regenerują, chroniąc przed kolejnymi uszkodzeniami. Obecność Pantenolu sprawia, że włosy są odżywione oraz dostają cienką warstwę ochronną, która wzmacnia włosy. W efekcie łatwo się je rozczesuje.','km','Szampon Londa Visible Repair','img/produkty/szampon-londa-visible-repair.png',44,'Londa','1000ml');
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`) VALUES ('Szampon Londa Professional Color Radiance skutecznie oczyszcza skórę głowy, dokładnie myje włosy i przywraca im naturalne piękno.','Produkt oparty jest na specjalnej formule Micro-Ions, wykorzystującej technikę Riadiolux, dzięki której mikrojony naorawiają naszę włosy. wprowadzając procesy naprawcze. Reakcja mikrojonów ze strukturą włosów następuje już w ciągu kilku pierwszych sekund, co sprawia, że efekt jest właściwie natychmiastowy. Szampon zawiera również polimery, które usuwają wszelkie zanieczyszczenia oraz pozostałości po produktach do stylizacji, dogłębnie odżywiając i oczyszczając włosy i skórę głowy. Dzięki ekstraktom z marakui oraz lipidom ze skórki pomarańczy produkt chroni kolor, utrwalając go i zapobiegając matowieniu.','km','Szampon Londa Color Radiance','img/produkty/szampon-londa-color-radiance.png',44,'Londa','1000ml');
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`) VALUES ('Serum Stapiz Ha Essence Aquatic z kwasem hialuronowym i wyciągiem z alg morskich to intensywna rewitalizacja osłabionych lub zniszczonych włosów.','Składniki aktywne skoncentrowane w ampułkach zapewniają głębokie nawilżenie, odżywienie oraz wygładzenie powierzchni włosa. Dzięki zawartym ekstraktom roślinnym serum wzmacnia włosy od cebulek aż po same końce. Już niewielka ilość preparatu przywraca zdrowy wygląd osłabionych włosów, jak również aktywizuje i wzmacnia je podczas okresowego wypadania.','km','Serum Ha essence','img/produkty/serum-ha-essence.png',5,'HA','8ml');
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`) VALUES ('Trychoxin, miesięczny program przeciw wypadaniu włosów zapobiega wypadaniu włosów dzięki najwyższej jakości substancjom aktywnym. Włosy stają się grubsze i silniejsze. Wspomaga odrost włosów.','24 aplikacje. Innowacyjne połączenie substancji aktywnych. Kompleksowy skład. Kuracja przeznaczona dla wzmocnienia włosów słabych i wypadających. Zapobiega wypadaniu włosów i wspomaga ich odrost. Pomaga włosom odzyskać zdrowy wygląd.','km','Ampułki przeciw wypadaniu włosów Trychoxin','img/produkty/trychoxin-ampulki-przeciw-wypadaniu-wlosow.png',120,'Trychoxin','12x9ml');
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`) VALUES ('Lekka odżywka WELLA PROFESSIONALS ELEMENTS przeznaczona do regeneracji wszystkich rodzajów włosów.','W składzie produktu siarczany i parabeny zostały zastąpione polimerami pochodzenia naturalnego, które wnikają w uszkodzoną powierzchnie włosa wzmacniając je, dając im gładkość i elastyczność. Zawarty w odżywce pantenol dba o odpowiednie nawilżenie włosów, a jej lekka formuła nie obciąża włosów.','km','Odżywka Wella Elements','img/produkty/szampon-wella-elements.png',95,'Wella','1000ml');
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`) VALUES ('Szampon Color Obsessed stworzony z myślą o włosach farbowanych. Formuła zawiera antyoksydanty, by chronić kolor dla zachowania jego intensywności nawet do 32 myć','Nawilżający szampon z przeciwutleniaczami, pomagający chronić kolor włosów przed blaknięciem. Szampon zachowuje fascynujący połysk włosów i przyczynia się do wydłużenia trwałości koloru włosów. Włosy stają się zdrowsze i mocniejsze.','km','Szampon Matrix Color Obsessed','img/produkty/szampon-matrix-color-obsessed.png',27,'Matrix','300ml');
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`) VALUES ('Szampon Matrix Total Results Texture Games skutecznie oczyszcza skórę głowy, dokładnie myje włosy i przywraca im naturalne piękno.','Szampon do codziennej pielęgnacji każdego rodzaju włosów. Szczególnie nadaje się do włosów falowanych. Zalecany do użytku domowego i profeslonajlnego. Dzięki produktowi możesz uzyskać określoną strukturę fryzury i zaprojektować stylizację. Dzięki unikalnemu połączeniu składników aktywnych szampon pozostawia na włosach lekko zmatowiony, plażowy efekt.','km','Szampon Matrix Texture Games','img/produkty/szampon-matrix-texture-games.png',27,'Matrix','300ml');
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`) VALUES ('Szampon Total Results Mega Sleek pielęgnuje, oczyszcza i nawilża. Wygładza i zapobiega puszeniu się włosów w ciągu dnia oraz chroni przed wilgocią.','Zawiera masło shea, które ma właściwości głęboko odżywiające i regenerujące. Dodatkowo nawilża włosy na całej ich długości, dzięki czemu stają się one gładkie i lśniące. Zawartość ceramidów gwarantuje także naprawę uszkodzeń w strukturze włosów oraz zwiększenie ich odporności na działanie szkodliwych czynników zewnętrznych.','km','Szampon Matrix Mega Sleek','img/produkty/szampon-matrix-mega-sleek.png',27,'Matrix','300ml');
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`) VALUES ('Szampon Matrix Total Results Curl Please  przeznaczony jest do włosów kręconych, puszących się.','Szampon został wzbogacony odżywczym olejkiem z nasion Jojoba, który poprawia elastyczność struktury włosa. Zawiera składniki myjące, które delikatnie oczyszczają włosy oraz skórę głowy. Technologia zapewnia maksymalne nawilżenie włosa, zatrzymuje wilgoć dzięki czemu włosy się nie puszą.','km','Szampon Matrix Curl Plase','img/produkty/szampon-matrix-curl-plase.png',27,'Matrix','300ml');
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`) VALUES ('Szampon do włosów cienkich i normalnych Wella Invigo Color Brilliance przeznaczony jest do pielęgnacji włosów farbowanych.','Kosmetyk ma optymalne pH, które zapewnia włosom długotrwałą ochronę. Co więcej nadaje włosom cudowny blask, zmiękcza je oraz wygładza. Szampon chroni włosy przed płowieniem koloru oraz nadaje włosom blask. Doskonale chroni przed czynnikami środowiskowymi. W składzie znajdują się molekuły miedzi, które podkreślają kolor i dodają blasku. Kawior z limonki  i technologia Anti-Oxidant Shield przeciwdziałają procesowi oksydacji, który przyspiesza blaknięcie koloru. ','km','Szampon Wella Color Brilliance','img/produkty/szampon-wella-color-brilliance.png',83,'Wella','1000ml');
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`) VALUES ('Specjalny szampon do pielęgnacji włosów suchych i zniszczonych. Nadaje włosom miękkość, witalność i zdrowy połysk.','Z kwasem oleinowym, nawilżającym pantenolem i witaminą E, która chroni włosy przed czynnikami zewnętrznymi (kompleks Nutri-Enrich). Maska do włosów zawiera również ekstrakt z jagód goji, które są znane z wysokiej zawartości witamin, minerałów i peptydów.','km','Szampon Wella Nutri-Enritch','img/produkty/szampon-wella-nutri-enrich.png',83,'Wella','1000ml');
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`) VALUES ('Szampon Wella Invigo Volume Boost Bodifying Shampoo - zagęszczająca pielęgnacja przeznaczona do włosów cienkich.','Szampon Wella Invigo Volume Boost skutecznie oczyszcza włosy w widoczny sposób dodając im objętości. Dzięki unikalnej formule zawierającej ekstrakt z bawełny i polimery, szampon zapewnia włosom wyjątkową pielęgnację nie obciążając ich. Kosmetyk sprawia, że włosy stają się grubsze, nawilżone i bardziej sprężyste. Szampon ponadto ułatwia uniesienie włosów podczas suszenia nadając fryzurze lekkości i blasku. ','km','Szampon Wella Volume Boost','img/produkty/szampon-wella-volume-boost.png',83,'Wella','1000ml');
   /* INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`) VALUES ('','','','','',,'',''); */

/* category */
INSERT INTO `SalonikBella`.`category` (`description`,`name`,`photo`) VALUE ('Szampony do włosów','szampon','img/produkty/category/szampony.png');
INSERT INTO `SalonikBella`.`category` (`description`,`name`,`photo`) VALUE ('Kosmetyki do stylizacji włosów','stylizacja','img/produkty/category/stylizacja.png');
INSERT INTO `SalonikBella`.`category` (`description`,`name`,`photo`) VALUE ('Serum do włosów','serum','img/produkty/category/serum.png');
INSERT INTO `SalonikBella`.`category` (`description`,`name`,`photo`) VALUE ('Kuracje do włosów','kuracje','img/produkty/category/kuracje.png');
INSERT INTO `SalonikBella`.`category` (`description`,`name`,`photo`) VALUE ('Odżywki i maski do włosów','odzywki-maski','img/produkty/category/odzywki-maski.png');
INSERT INTO `SalonikBella`.`category` (`description`,`name`,`photo`) VALUE ('Farby do włosów','farby','img/produkty/category/farby.png');
INSERT INTO `SalonikBella`.`category` (`description`,`name`,`photo`) VALUE ('Produkty do kreatynowego prostowania','kreatyna','img/produkty/category/kreatyna.png');

/* product - category */
INSERT INTO `SalonikBella`.`category_products` (`category_id`,`product_id`) VALUE (4,1);
INSERT INTO `SalonikBella`.`category_products` (`category_id`,`product_id`) VALUE (5,1);
INSERT INTO `SalonikBella`.`category_products` (`category_id`,`product_id`) VALUE (2,2);
INSERT INTO `SalonikBella`.`category_products` (`category_id`,`product_id`) VALUE (2,3);
INSERT INTO `SalonikBella`.`category_products` (`category_id`,`product_id`) VALUE (2,4);
INSERT INTO `SalonikBella`.`category_products` (`category_id`,`product_id`) VALUE (2,5);
INSERT INTO `SalonikBella`.`category_products` (`category_id`,`product_id`) VALUE (5,6);
INSERT INTO `SalonikBella`.`category_products` (`category_id`,`product_id`) VALUE (4,7);
INSERT INTO `SalonikBella`.`category_products` (`category_id`,`product_id`) VALUE (5,7);
INSERT INTO `SalonikBella`.`category_products` (`category_id`,`product_id`) VALUE (2,8);
INSERT INTO `SalonikBella`.`category_products` (`category_id`,`product_id`) VALUE (2,9);
INSERT INTO `SalonikBella`.`category_products` (`category_id`,`product_id`) VALUE (2,10);
INSERT INTO `SalonikBella`.`category_products` (`category_id`,`product_id`) VALUE (4,11);
INSERT INTO `SalonikBella`.`category_products` (`category_id`,`product_id`) VALUE (5,11);
INSERT INTO `SalonikBella`.`category_products` (`category_id`,`product_id`) VALUE (5,12);
INSERT INTO `SalonikBella`.`category_products` (`category_id`,`product_id`) VALUE (5,13);
INSERT INTO `SalonikBella`.`category_products` (`category_id`,`product_id`) VALUE (1,14);
INSERT INTO `SalonikBella`.`category_products` (`category_id`,`product_id`) VALUE (1,15);
INSERT INTO `SalonikBella`.`category_products` (`category_id`,`product_id`) VALUE (1,16);
INSERT INTO `SalonikBella`.`category_products` (`category_id`,`product_id`) VALUE (1,17);
INSERT INTO `SalonikBella`.`category_products` (`category_id`,`product_id`) VALUE (3,18);
INSERT INTO `SalonikBella`.`category_products` (`category_id`,`product_id`) VALUE (3,19);
INSERT INTO `SalonikBella`.`category_products` (`category_id`,`product_id`) VALUE (5,20);
INSERT INTO `SalonikBella`.`category_products` (`category_id`,`product_id`) VALUE (1,21);
INSERT INTO `SalonikBella`.`category_products` (`category_id`,`product_id`) VALUE (1,22);
INSERT INTO `SalonikBella`.`category_products` (`category_id`,`product_id`) VALUE (1,23);
INSERT INTO `SalonikBella`.`category_products` (`category_id`,`product_id`) VALUE (1,24);
INSERT INTO `SalonikBella`.`category_products` (`category_id`,`product_id`) VALUE (1,25);
INSERT INTO `SalonikBella`.`category_products` (`category_id`,`product_id`) VALUE (1,26);
INSERT INTO `SalonikBella`.`category_products` (`category_id`,`product_id`) VALUE (1,27);
    /* INSERT INTO `SalonikBella`.`category_products` (`category_id`,`product_id`) VALUE (1,2); */

    /* UserRole */
    INSERT INTO `SalonikBella`.`user_role` (`role`, `description`) VALUES ('USER', 'default role for user');
INSERT INTO `SalonikBella`.`user_role` (`role`, `description`) VALUES ('ADMIN', 'role for the administrator');

/* User */
INSERT INTO `SalonikBella`.`user` (`email`,`first_name`,`last_name`,`password`,`role_id`) VALUES ('kamil@gmail.com','Kamil','B','{bcrypt}$2y$12$F69c5ffmSm/7NUmvR86ZS.uIUKIFloqA9tNdalKJWoWwarY6eO.fi',2);
INSERT INTO `SalonikBella`.`user` (`email`,`first_name`,`last_name`,`password`,`role_id`) VALUES ('michal@gmail.com','Michał','G','{bcrypt}$2y$12$ujUlLqKAnBtjBYzybGdNW.Dp70G1ftwJ5C/sjT/HK45GYQCNGtGQC',1);


/* Koszyk Perfum */
INSERT INTO `SalonikBella`.`user_perfume_list` (`user_id`,`perfume_list_id`) VALUES (1,2);
INSERT INTO `SalonikBella`.`user_perfume_list` (`user_id`,`perfume_list_id`) VALUES (1,3);
INSERT INTO `SalonikBella`.`user_perfume_list` (`user_id`,`perfume_list_id`) VALUES (1,4);

/* Koszyk Produktow */
INSERT INTO `SalonikBella`.`user_product_list` (`user_id`,`product_list_id_product`) VALUES (1,1);

/* Visits */
INSERT INTO `SalonikBella`.`visit` (`admin_info`,`visit_begin`,`visit_end`,`phone`,`status`,`user_info`,`haircut_type_id`,`user_id`) VALUES ('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent condimentum at nulla a tincidunt. Aliquam metus urna, porttitor nec ligula nec, varius ultricies arcu. Mauris imperdiet ullamcorper magna, ac lacinia odio luctus porttitor. ','2021/01/01T15:00','2021/01/01T15:20',123123123,0,'strzyzenie meskie',1,1);
INSERT INTO `SalonikBella`.`visit` (`admin_info`,`visit_begin`,`visit_end`,`phone`,`status`,`user_info`,`haircut_type_id`,`user_id`) VALUES ('','2021/01/10T15:00','2021/01/10T15:20',123123123,1,'strzyzenie meskie',1,1);
INSERT INTO `SalonikBella`.`visit` (`admin_info`,`visit_begin`,`visit_end`,`phone`,`status`,`user_info`,`haircut_type_id`,`user_id`) VALUES ('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent condimentum at nulla a tincidunt. Aliquam metus urna, porttitor nec ligula nec, varius ultricies arcu. Mauris imperdiet ullamcorper magna, ac lacinia odio luctus porttitor. ','2021/01/15T15:00','2021/01/15T15:20',123123123,0,'strzyzenie meskie',1,1);
INSERT INTO `SalonikBella`.`visit` (`admin_info`,`visit_begin`,`visit_end`,`phone`,`status`,`user_info`,`haircut_type_id`,`user_id`) VALUES ('','2021/01/19T09:00','2021/01/19T09:20',987987987,0,'strzyzenie meskie',1,2);
INSERT INTO `SalonikBella`.`visit` (`admin_info`,`visit_begin`,`visit_end`,`phone`,`status`,`user_info`,`haircut_type_id`,`user_id`) VALUES ('','2021/01/19T16:00','2021/01/19T16:20',987987987,0,'strzyzenie meskie strzyzenie meskie strzyzenie meskie ',1,2);

/* List wizyt klientow */
INSERT INTO `SalonikBella`.`user_visit_list` (`user_id`,`visit_list_id`) VALUES (1,1);
INSERT INTO `SalonikBella`.`user_visit_list` (`user_id`,`visit_list_id`) VALUES (1,2);
INSERT INTO `SalonikBella`.`user_visit_list` (`user_id`,`visit_list_id`) VALUES (1,3);
INSERT INTO `SalonikBella`.`user_visit_list` (`user_id`,`visit_list_id`) VALUES (2,4);
INSERT INTO `SalonikBella`.`user_visit_list` (`user_id`,`visit_list_id`) VALUES (2,5);









