/* uslugi fryzjerskie */
INSERT INTO `SalonikBella`.`haircut` (`description`,`gender`,`max_price`,`name`, `price`) VALUES ('strzyżenie męskie',0,0,'strzyżenie męskie',25);
INSERT INTO `SalonikBella`.`haircut` (`description`,`gender`,`max_price`,`name`, `price`) VALUES ('strzyżenie dzieci',2,30,'strzyżenie dzieci',25);
INSERT INTO `SalonikBella`.`haircut` (`description`,`gender`,`max_price`,`name`, `price`) VALUES ('Strzyżenie damskie z modelowaniem',1,50,'Strzyżenie damskie z modelowaniem',40);
INSERT INTO `SalonikBella`.`haircut` (`description`,`gender`,`max_price`,`name`, `price`) VALUES ('Koloryzacja odrostów',1,0,'Koloryzacja odrostów',100);
INSERT INTO `SalonikBella`.`haircut` (`description`,`gender`,`max_price`,`name`, `price`) VALUES ('Pasemka, ombre',1,160,'Pasemka, ombre',110);
INSERT INTO `SalonikBella`.`haircut` (`description`,`gender`,`max_price`,`name`, `price`) VALUES ('Fryzury okolicznościowe',1,130,'Fryzury okolicznościowe',40);
INSERT INTO `SalonikBella`.`haircut` (`description`,`gender`,`max_price`,`name`, `price`) VALUES ('Styling (trwała)',1,0,'Styling (trwała)',100);
INSERT INTO `SalonikBella`.`haircut` (`description`,`gender`,`max_price`,`name`, `price`) VALUES ('Keratynowe prostowanie włosów',1,350,'Keratynowe prostowanie włosów',250);
INSERT INTO `SalonikBella`.`haircut` (`description`,`gender`,`max_price`,`name`, `price`) VALUES ('Nawilżanie włosów ',1,0,'Nawilżanie włosów ',60);

/* perfumy 15 ml */
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Eksplozja nut cytrusowych tworzy bardzo pociągający zapach. Delikatne akordy piżma napawają  pogodnym nastawieniem.','BRAK','m','beach','img/perfumy/beach/beach15.jpg',25,'Aromatyczno - Drzewna, Beach to zrównoważony, czysty zapach. Idealny dla kobiet i mężczyzn. Nuty głowy: Pomarańcza, nuty serca: Konwalia, nuty bazy: Piżmo.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Fuzja nut hesperydowych z cyklamenem i nutami drzewnymi pozwoliła na stworzenie ekspresywnego zapachu pachnącego wolnością.','BRAK','m','acqua per uomo','img/perfumy/acqua-per-uomo/acqua-per-uomo15.jpg',25,'Aromatyczno - Wodna. Acqua per uomo to świeży zapach dla naturalnego i współczesnego mężczyzny. Nuty głowy: Bergamotka, nuty serca  Cyklamen, nuty bazy: Drzewo.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Te perfumy pełne aromatycznych nut nadają mężczyźnie, który ich używa uwodzicielskiego i prawdziwie męskiego charakteru.','BRAK','m','WOW SCENT!','img/perfumy/wow-scent!/wow-scent!15.jpg',25,'Paprociowo – Korzenny. Wow Scent! to męskie perfumy dla żywiołowego I radosnego mężczyzny. Nuty głowy: Mięta, nuty serca: Szałwia, nuty bazy: Wanilia','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Uwodzicielska i intensywna kompozycja zapachowa będąca połączeniem pogodnej maliny z miękką gardenią i ciepłem paczuli.','BRAK','k','power woman','img/perfumy/power-woman/power-woman15.jpg',25,'Power Woman to zapach pełen oryginalnych kontrastów. Dla ambitnej kobiety z charakterem. Nuty głowy: Malina, nuty serca: Gardenia, nuty bazy: Paczuli.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Odczuwalna świeżość mandarynki w połączeniu z esencjami gardenią i drzewa sandałowego tworzy wyjątkowo wyrafinowany zapach.','BRAK','k','notion woman','img/perfumy/notion-woman/notion-woman15.jpg',25,'Kwiatowo - Owocowa. Notion Woman to zapach dla wesołej, dynamicznej kobiety, emanującej optymizmem i elegancją. Nuty głowy: Mandarynka, nuty serca: Gardenia, nuty bazy: Sandał.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Mocno pudrowy aromat białych kwiatów, orientalne tło i ciepło kwiatowego bukietu odzwierciedlają zmysłowość i delikatność. ','BRAK','k','VELFASHION','img/perfumy/velfashion/velfashion15.jpg',25,'Orientalno - Waniliowa. Velfashion  to złożony i elegancki zapach. Dla kobiety z wdziękiem i charyzmą. Nuty głowy: Bergamotka, nuty serca: Jaśmin, nuty bazy: Wetiweria pachnąca.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Uwodzicielska fuzja cytryny, imbiru i kardamonu daje w efekcie pocigąjący i niezapomniany zapach','BRAK','m','west','img/perfumy/west/west15.jpg',25,'Szyprowo-Drzewna. West to perfumy dla odważnego i charyzmatycznego mężczyzny. Nuty głowy: Cytryna, nuty serca: Kardamon, nuty bazy: Bób tonka','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Silne nuty bergamotki i lawendy nadają kompozycji klasyczny męski charakter, które łagodzi delikatny aromat ambry.','BRAK','m','CARIBBEAN','img/perfumy/caribbean/caribbean15.jpg',25,'Paprociowo - Ambrowa. Caribbean jest to świeży zapach dla prawdziwego i przebojowego mężczyzny. Nuty głowy: Bergamotka, nuty serca: Lavenda, nuty bazy: Bursztyn','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Charakterystyczna piramida zapachowa, w której dominują nuty orientalne, tworzy zapach emanujący siłą i trwałością.','BRAK','m','INSTINT','img/perfumy/instint/instint15.jpg',25,'Orientalno - Korzenna. Instint to zapach wyjątkowo prowokacyjny. Dla odważnego i seksownego mężczyzny. Nuty głowy: Kwiat pomarńczy, nuty serca: Lavenda, nuty bazy: Wanilia.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Orzeźwiający i zmysłowy zapach wykreowany dzięki połączeniu energicznych i intensywnych nut drzewnych ze słodyczą jaśminu.','BRAK','m','platinum','img/perfumy/platinum/platinum15.jpg',25,'Drzewno - wodna. Platinum  to zapach pełen mocy. Dla aktywnego, uwielbiającego przygody mężczyzny. Nuty głowy: Grejpfrut, nuty serca: Jaśmin, nuty bazy: Drzewo.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Owocowe nuty głowy ustępują ciepłym nutom drzewnym kreując wyrafinowany i elegancki zapach.','BRAK','m','MOMENT','img/perfumy/moment/moment15.jpg',25,'Orientalno - drzewna. Moment to elegancki, czysty zapach. Dla mężczyzny pewnego siebie. Nuty głowy: Jabłko, nuty serca: Cynamon, nuty bazy: Drzewo.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Nowoczesne połączenie swieżych i iskrzących akordów zapewniają temu zapachowi zmysłowość, wyrazistość i osobowość.','BRAK','m','metal sport','img/perfumy/metal-sport/metal-sport15.jpg',25,'Szyprowo - Owocowa. Metal Sport to zapach dla atrakcyjnego, uwodzicielskiego i energicznego mężczyzny. Nuty głowy: Mandarynka, nuty serca: Drzewo, nuty bazy: Wetiweria pachnąca.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Otulający aromat piżma i elegancja białej róży kształtuje perfumy o namiętnej zmysłowości.','BRAK','k','nicolas white','img/perfumy/nicolas-white/nicolas-white15.jpg',25,'Kwiatowo-Drzewna. Nicolás White jest to piżmowo- kwiatowy zapach dla bardzo zmysłowej kobiety. Nuty głowy: Biała róża, nuty serca : Piżmo, nuty bazy: Biały cedr.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Owocowe i aksamitne nuty granatu, wraz z  czarującą wonią orchidei i fiołka, tworzą odważny i wykwintny zapach.','BRAK','k','aroma','img/perfumy/aroma/aroma15.jpg',25,'Orientalno - Kwiatowa. Aroma to  egzotyczny i nadający blask zapach. Dla eleganckiej i tajemniczej kobiety. Nuty głowy: Granat, nuty serca: Orchidea, nuty bazy: Fiołek.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Nowoczesna kompozycja aromatyczna tworzy odważny zapach, odzwierciedlający luksus i elegancję.','BRAK','k','cheante','img/perfumy/cheante/cheante15.jpg',25,'Szyprowo - Kwiatowa. Cheante to  kobiecy i zmysłowy zapach. Dla eleganckiej i szykownej kobiety. Nuty głowy: Bergamotka, nuty serca: Róża, nuty bazy: Piżmo.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Współczesna i luksusowa kompozycja zapachowa powstała z połączenia wibrujących nut głowy z namiętną fuzją  jaśminu i wetywerii.','BRAK','k','SOPHISTICATE','img/perfumy/sophiesticate/sophiesticate15.jpg',25,'Orientalno - Kwiatowa. Sophisticate to zmysłowy zapach. Dla namiętnej i silnej kobiety. Nuty głowy: Liczi, nuty serca: Jaśmin, nuty bazy: Wetiweria pachnąca.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Pociągające słodkie nuty czarnej porzeczki i silna obecność wanilii sprawiają, iż od samego początku perfumy posiadają własną osobowość.','BRAK','k','adriana','img/perfumy/adriana/adriana15.jpg',25,'Szyprowo - Owocowa. Pociągające słodkie nuty czarnej porzeczki i silna obecność wanilii sprawiają, iż od samego początku perfumy posiadają własną osobowość. Nuty głowy: Czarna porzeczka,nuty serca: Wanilia, nuty bazy: Drzewo.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Świeżość bergamotki i elegancja róży z dodatkiem waniliowej głębi tych perfum, nadają im ponadczasowy i nowoczesny charakter.','BRAK','k','ADRIANA ROSE','img/perfumy/adriana-rose/adriana-rose15.jpg',25,'Chypre Fruity. Jest to elegancki i niepowtarzalnie kobiecy zapach. Nuty głowy: Bergamotka, nuty serca: Róża, nuty bazy: Wanilia.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Świeżość grejpfruta, delikatność jaśminu oraz poetyckie połączenie ambry tworzy perfumy słodkie i cytrusowe.','BRAK','k','for you','img/perfumy/for-you/for-you15.jpg',25,'Kwiatowo-Owocowy. For You są to subtelne i delikatne perfumy dla optymistycznej kobiety. Nuty głowy: Bergamotka, Grejpfrut, nuty serca: Jaśmin, nuty bazy: Bursztyn, Biały cedr.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Zmysłowy zapach będący połączeniem delikatnego jabłka i bambusu, które nadają świeżych akrodów nutą drzewnym.','BRAK','k','kara','img/perfumy/kara/kara15.jpg',25,'Kwiatowo - Owocowa. Kara to pobudzający zapach. Dla radosnej, cieszącej się życiem kobiety. Nuty głowy: Jabłko, nuty serca: Bambus, nuty bazy: Piżmo.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Intensywne połączenie białych kwiatów i bobu tonka tworzy odważne i wyszukane perfumy.','BRAK','k','very special','img/perfumy/very-special/very-special15.jpg',25,'Orientalno - Kwiatowa. Very Special to perfumy dla wpływowej i namiętnej kobiety. Nuty głowy: Tuberoza, Migdały, nuty serca: Jaśmin, nuty bazy: Bób tonka.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Zapach otulony miękkością i czułością dzięki harmonijnemu połączeniu nut zapachowych. Jego pudrowe nuty upajają marzeniami.','BRAK','k','SEDUCCIÓN','img/perfumy/seduccion/seduccion15.jpg',25,'Kwiatowo - Kwiatowa. Seducción to słodki, ujmujący zapach. Dla wyjątkowej i delikatnej kobiety. Nuty głowy: Piwonia, nuty serca: Konwalia, nuty bazy: Piżmo.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Kwiatowa etuida wraz z nutami wanilii tworzy niezapomniany zapach pudrowy. Delikatny a zarazem silny i wyjątkowy aromat rozbudza niezliczone doznania.','BRAK','k','berlue','img/perfumy/berlue/berlue15.jpg',25,'Kwiatowo - Aldehydowa. Berlue to  ponadczasowy zapach. Dla kobiety uwielbiającej klasyczny i elegancki styl. Nuty głowy: Kwiat pomarńczy, nuty serca: Róża, nuty bazy: Wanilia.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Dominujący zapach wanilii sprawia, że zapach ten jest urzekający i charyzmatyczny. ','BRAK','k','temis','img/perfumy/temis/temis15.jpg',25,'Orientalno - Kwiatowa. Temis to perfumy dla kobiety tajemniczej i prowokującej. Nuty głowy: Kwiat Imbiru, nuty serca: Jaśmin Wodny, nuty bazy: Wanilia.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Zapach elegancki i zmysłowy, powstały z kreatywnego połączenia nut cytrusowych z cynamonem i świeżą paczulą.','BRAK','m','power','img/perfumy/power/power15.jpg',25,'Power to intesywny, pobudzający zapach. Dla uwodzicielskiego, tajemniczego mężczyzny. Nuty głowy: Grejpfrut, nuty serca: Cynamon, nuty bazy: Paczuli.','15');

/* perfumy 50 ml */
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Zapach elegancki i zmysłowy, powstały z kreatywnego połączenia nut cytrusowych z cynamonem i świeżą paczulą.','BRAK','m','power','img/perfumy/power/power50.jpg',999,'Power to intesywny, pobudzający zapach. Dla uwodzicielskiego, tajemniczego mężczyzny. Nuty głowy: Grejpfrut, nuty serca: Cynamon, nuty bazy: Paczuli.','50');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Żywe cytrusowe nuty harmonijnie otaczają spokojny aromat róży, nadając życiu radosny i delikatny zapach.','BRAK','k','vivacity','img/perfumy/vivacity/vivacity50.jpg',999,'Vivacity  to zapach dla żywiołowej i słodkiej kobiety. Nuty głowy: Mandarynka, nuty serca: Róża Grasse, nuty bazy: Drzewo sandałowe.','50');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Świeżość bergamotki i imbiru kontrastuje z zapachem jabłka, a nuty szałwii, jałowca i lawendy gwarantują zapach silnej męskości.','BRAK','m','resolu','img/perfumy/resolu/resolu50.jpg',999,'Reslou dla energicznego i wytrwałego mężczyzny. Nuty głowy: Bergamotka, Jabłko, Imbir, nuty serca: Jałowieć, Lawenda, Szałwia , nuty bazy: Drewno bursztynowe, Olibanum, Fasolka tonka.','50');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Intensywność bergamotki i kakao sprawiają, że te perfumy są niezapomnianym przeżyciem, które sprawi, że przemierzysz cały świat.','BRAK','m','peak','img/perfumy/peak/peak50.jpg',999,'Peak dla mężczyzny pełnego życia z charakterem. Nuty głowy: Bergamotka, nuty serca: Skóra, nuty bazy: Kakao.','50');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Cytrusowy dotyk bergamotki wraz z urzekającymi nutami tuberozy i paczuli tworzą intensywny i kobiecy zapach.','BRAK','k','tendenze','img/perfumy/tendenze/tendenze50.jpg',999,'Tendenze to mocny cytrusowo kwiatowy zapach. Idealny dla eleganckiej i odważnej kobiety. Nuty głowy: Bergamotka, nuty serca: Tuberoza, nuty bazy: Paczula.','50');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Zmysłowość nut zapachowych, które tworzą te perfumy sprawia, że kobieta, która ich używa jest namiętna i nie można się jej oprzeć.','BRAK','k','suerte','img/perfumy/suerte/suerte50.jpg',999,'Suerte to  zapach dla uwodzicielskiej i uroczej kobiety. Nuty głowy: Ylang-ylang, nuty serca: Wanilia, nuty bazy: Białe Piżmo.','50');

/* perfumy 100 ml */
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Owocowe i aksamitne nuty granatu, wraz z  czarującą wonią orchidei i fiołka, tworzą odważny i wykwintny zapach.','BRAK','k','aroma','img/perfumy/aroma/aroma100.jpg',999,'Orientalno - Kwiatowa. Aroma to  egzotyczny i nadający blask zapach. Dla eleganckiej i tajemniczej kobiety. Nuty głowy: Granat, nuty serca: Orchidea, nuty bazy: Fiołek.','100');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Odczuwalna świeżość mandarynki w połączeniu z esencjami gardenią i drzewa sandałowego tworzy wyjątkowo wyrafinowany zapach.','BRAK','k','notion woman','img/perfumy/notion-woman/notion-woman100.jpg',999,'Kwiatowo - Owocowa. Notion Woman to zapach dla wesołej, dynamicznej kobiety, emanującej optymizmem i elegancją. Nuty głowy: Mandarynka, nuty serca: Gardenia, nuty bazy: Sandał.','100');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Uwodzicielska i intensywna kompozycja zapachowa będąca połączeniem pogodnej maliny z miękką gardenią i ciepłem paczuli.','BRAK','k','power woman','img/perfumy/power-woman/power-woman100.jpg',999,'Power Woman to zapach pełen oryginalnych kontrastów. Dla ambitnej kobiety z charakterem. Nuty głowy: Malina, nuty serca: Gardenia, nuty bazy: Paczuli.','100');

/* pictures */
INSERT INTO `SalonikBella`.`picture` (`description`,`name`,`path`,`title`) VALUES ('','','img/galeria/picture1.jpg','');
INSERT INTO `SalonikBella`.`picture` (`description`,`name`,`path`,`title`) VALUES ('','','img/galeria/picture2.jpg','');
INSERT INTO `SalonikBella`.`picture` (`description`,`name`,`path`,`title`) VALUES ('','','img/galeria/picture3.jpg','');
INSERT INTO `SalonikBella`.`picture` (`description`,`name`,`path`,`title`) VALUES ('','','img/galeria/picture4.jpg','');
/* INSERT INTO `SalonikBella`.`picture` (`description`,`name`,`path`,`title`) VALUES ('','','','');*/

/* products */
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`,`category_id`) VALUES ('Odżywka 3 SYSTEM to unikalna formuła (bez spłukiwania) zawierająca pantenol, glikol propylenowy, ceramidy, aminokwasy jedwabiu oraz kompleks wyselekcjonowanych polimerów i składników kondycjonujących.','Tak bogata, starannie skomponowana receptura zapewnia aż 15 imponujących efektów: nawilża, wypełnia strukturę włókna włosa, redukując jego porowatość, wzmacnia spoiwo międzykomórkowe włosów, zapobiega puszeniu się włosów, wygładza, ułatwia rozczesywanie, ułatwia prostowanie, nadaje połysk, zapobiega rozdwajaniu końcówek, odżywia włosy, zmiękcza, sprawia, że włosy stają się bardziej sypkie, uelastycznia włókno włosa, redukuje skłonność do łamania się włosów, zapobiega elektryzowaniu.','km','odżywka 3 system EssentialSalon','img/produkty/profis-3-spectacular-essentialsalon.png',999,'EssentialSalon','250ml',1);
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`,`category_id`) VALUES ('Mgiełka Podnosząca Włosy u nasady ProSalon Intensis Hair Booster Mist.','Przeznaczona do włosów cienkich i delikatnych. Dzięki zastosowaniu innowacyjnych składników aktywnych zapewnia uzyskanie efektu zwiększonej objętości włosów. Wzmacnia i unosi włosy u nasady, dzięki czemu fryzura zyskuje lekkość i puszystość. Obecne w preparacie proteiny pszenicy pomagają utrzymać prawidłowy poziom nawilżenia, przez co włosy stają się gładkiej błyszczące. Filtr UV chroni włosy przed działaniem szkodliwych zewnętrznych czynników.','km','Mgiełka Podnosząca Włosy Intensis','img/produkty/prosalon-intensis.png',999,'Chantal','200g',1);
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`,`category_id`) VALUES (' Spray do nabłyszczenia Schwarzkopf Professional Osis+ Sparkler Finish delikatnie utrwali twoją fryzurę i nada jej olśniewającego blasku.','Właściwości: utrwala fryzurę, przynosi wykończenie pełne blasku, pomaga stworzyć wymarzoną fryzurę','km','Osis+ Sparkler Finish Schwarzkopf','img/produkty/osis-sparkler.png',999,'SchwarzkopfProfessional','300ml',1);
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`,`category_id`) VALUES ('Zapewnia intensywne i niezrównane utrwalenie.','Utrzymuje fryzurę w mokrych warunkach. Można go łatwo usunąć za pomocą lekkiego szczotkowania.','km','spray do włosów GODET Yodeyma','img/produkty/yodeyma-godet.png',999,'Yodeyma','300ml',1);
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`,`category_id`) VALUES ('Guma do stylizacji OSiS Thrill posiada mocną, elastyczną, włóknistą strukturę, która bardzo mocno utrwala stylizowaną fryzurę. Nadaje wysoki połysk i gwarantuje bardzo dobrą separację pojedynczych pasm.','Pozwala na modelowanie włosów, nie obciążając ich nadmiernie. Skutecznie utrzymuje pożądany kształt fryzury i nadaje pasmom naturalny połysk. SCHWARZKOPF OSiS+ Thrill to łatwe układanie włosów krótkich i średniej długości. Produkt jest wydajny, przetestowany dermatologicznie. Można go stosować na suche lub lekko wilgotne włosy.','m','Osis+ Thrill Guma do stylizacji','img/produkty/osis-hairgum.png',999,'SchwarzkopfProfessional','100ml',1);
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`,`category_id`) VALUES ('Chantal Prosalon Argan Oil Gold Serum Hair Repair Serum do włosów z olejkiem arganowym','Lekka odżywka znakomita do pielęgnacji wszystkich rodzajów włosów, a w szczególności do włosów zniszczonych, suchych i szorstkich. Formuła odżywki jest oparta na olejku arganowym, który doskonale odżywia włosy, przywraca im zdrowy wygląd, gładkość i połysk. Odżywka szybko się wchłania, ułatwia rozczesywanie. Nie obciąża włosów.','km','odżywka do włosów ARGAN OIL','img/produkty/arganoil-prosalon.png',999,'ProSalon','100ml',1);
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`,`category_id`) VALUES ('Maska zakwaszająca do włosów Stapiz Acid Balance Hair Mask to profesjonalny produkt o nowoczesnym działaniu. Czas na prawdziwą głębię koloru!','Unikalna formuła o kwaśnym pH pomaga utrzymać pukle w nieskazitelnej kondycji, a do tego dzięki zawartości filtrów UV chroni jest przed blaknięciem pod wpływem słońca. Za ochronę nowego odcienia i jego wieczny blask odpowiada miks wyciągów z cytrusów i winogron. Towarzyszą im odżywcze proteiny jedwabiu o funkcji wzmacniającej. Wnikają w głąb włókien i zapobiegają ich łamaniu się i kruszeniu, do tego kontrolują gospodarkę wodną.','km','Stapiz Maska Zakwaszająca Do Włosów','img/produkty/snapiz-acid-balance.png',999,'Stapiz','500ml',1);
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`,`category_id`) VALUES ('Pianka do układania włosów z ceramidami eliminuje elektryzowanie się włosów, zwiększa objętość, nadaje połysk i zapewnia długotrwałe utrwalenie fryzury.','Dzięki swojemu składowi regeneruje i zabezpiecza włosy przed czynnikami zewnętrznymi takimi jak słońce, wiatr, słona woda.','km','Pianka do włosów Black Equal Strong','img/produkty/blackprofessional-mousse-ristrutturante.png',999,'Black','400ml',1);
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`,`category_id`) VALUES ('Lakier do włosów ekstra strong z Pantenolem - jego formuła , bogata w Pantenol nadaje włosom nową siłę oraz zapewnia pełne nawilżenie, przywracając włosom fizjologiczną równowagę.','Zapewnia  lekką stylizację ,nadając  połysk i objetość o długotrwałym efekcie. Nie moczy włosów, nie działa na ich strukturę, wzmacniając je bez wpływania na ich naturalną elastyczność. Lakier ten chroni przed szkodliwym wpływem wilgoci i czynników atmosferycznych dzięki zawartości. Nie zostawia po sobie śladów.','km','Lakier do włosów LACCA SPRAY ','img/produkty/allwaves-laccaspray.png',999,'Allwaves','750ml',1);
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`,`category_id`) VALUES ('Puder zwiększający objętość włosów Prosalon Intensis Volumizing Powder Push-Up sygnowany marką Chantal Gandalf.com.pl','Stworzony z myślą o pielęgnacji włosów cienkich, płaskich i wiotkich. Nadaje natychmiastową objętość włosom bez ich obciążania. Unosi włosy u nasady, dzięki czemu fryzura zyskuje naturalną lekkość i puszystość. Specjalnie opracowana formuła absorbuje nadmiar sebum, przywracając świeży wygląd włosom przetłuszczonym i obciążonym. Puder nie skleja włosów, nadaje efekt matowego wykończenia.','k','Puder zwiększający objętość włosów Intensis','img/produkty/voluming-powder-intensis.png',999,'ProSalon','20g',1);
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`,`category_id`) VALUES ('Schwarzkopf BC Bonacure Time Restore Q10 Night Spray odżywczy spray na noc do włosów dojrzałych','Głęboko odżywiająca, intensywna maseczka na noc, o kremowej konsystencji w sprayu. Tzw. "Strażnik Czasu" z koenzymem Q10 wzmacnia osłabione i podatne na łamanie i wypadanie włosy.Nadaje im intensywny połysk i gładkość. Wspomaga wzrost zdrowych włosów. Szybko schnący. zawarty w składzie sprayu na noc koenzym Q10 – reaktywuje proces produkcji dwóch niezbędnych rodzajów keratyny, który wraz z upływem czasu ulega spowolnieniu. Nie pozostawia osadu na poduszce.','km','spray odżywczy Schwarzkopf Q10 Night','img/produkty/q10-night-spray.png',999,'SchwarzkopfProfessional','100ml',1);
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`,`category_id`) VALUES ('O’REVLE BIOCEANA ELIXIRO to odżywka dwufazowa o ekspresowym działaniu, która polecana jest do włosów zniszczonych, przetłuszczających się, oraz trudnych do rozczesania.','Twoje włosy stają się odżywione, wygładzone i doskonale nawilżone. Formuła elixiru rozświetla je i zapewnia ochronę przed wysokimi temperaturami oraz nadmiernym wysuszeniem podczas stylizacji. Włosy doskonale się rozczesują i mniej przetłuszczają, a co za tym idzie dłużej zachowują lekkość i sprężystość.','km','Odżywka dwufazowa O’REVLE BIOCEANA','img/produkty/odzywka-biocena.png',999,'Scandic','250ml',1);
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`,`category_id`) VALUES ('maska do włosów Stapiz Ha Essence pozwala zregenerować, odbudować oraz właściwie nawilżyć swoje suche i zniszczone włosy.','zawiera kwas hialuronowy i algi. Składniki te znane są z doskonałego działania nawilżającego, dzięki czemu maska Ha Essence przywraca włosom odpowiedni poziom wilgoci. Algi w zawarte w formule kosmetyku zaopatrują też włosy w aminokwasy, składniki mineralne oraz proteiny. Pasma stają się sprężyste, miękkie i gładkie w dotyku. Odżywka Stapiz ułatwia również rozczesywanie włosów, co sprawia, że codzienna pielęgnacja staje się przyjemnością.','km','maska do włosów Ha Essence','img/produkty/maska-ha-essence.png',999,'Stapiz','1000ml',1);


/* INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`,`category_id`) VALUES ('','','','','',,'','',  ''); */

/* category */
INSERT INTO `SalonikBella`.`category` (`description`,`name`,`photo`) VALUE ('Szampony do włosów','szampon','img/produkty/category/szampony.png');
INSERT INTO `SalonikBella`.`category` (`description`,`name`,`photo`) VALUE ('Kosmetyki do stylizacji włosów','stylizacja','img/produkty/category/stylizacja.png');
INSERT INTO `SalonikBella`.`category` (`description`,`name`,`photo`) VALUE ('Serum do włosów','serum','img/produkty/category/serum.png');
INSERT INTO `SalonikBella`.`category` (`description`,`name`,`photo`) VALUE ('Kuracje do włosów','kuracje','img/produkty/category/kuracje.png');
INSERT INTO `SalonikBella`.`category` (`description`,`name`,`photo`) VALUE ('Odżywki i maski do włosów','odzywki-maski','img/produkty/category/odzywki-maski.png');
INSERT INTO `SalonikBella`.`category` (`description`,`name`,`photo`) VALUE ('Farby do włosów','farby','img/produkty/category/farby.png');
INSERT INTO `SalonikBella`.`category` (`description`,`name`,`photo`) VALUE ('Produkty do kreatynowego prostowania','kreatyna','img/produkty/category/kreatyna.png');

























