/* uslugi fryzjerskie */
INSERT INTO `SalonikBella`.`haircut` (`description`,`gender`,`max_price`,`name`, `price`) VALUES ('strzyżenie męskie',0,0,'strzyżenie męskie',25);
INSERT INTO `SalonikBella`.`haircut` (`description`,`gender`,`max_price`,`name`, `price`) VALUES ('strzyżenie dzieci',2,30,'strzyżenie dzieci',25);
INSERT INTO `SalonikBella`.`haircut` (`description`,`gender`,`max_price`,`name`, `price`) VALUES ('Strzyżenie damskie z modelowaniem',1,50,'Strzyżenie damskie z modelowaniem',40);
INSERT INTO `SalonikBella`.`haircut` (`description`,`gender`,`max_price`,`name`, `price`) VALUES ('Koloryzacja odrostów',1,0,'Koloryzacja odrostów',100);
INSERT INTO `SalonikBella`.`haircut` (`description`,`gender`,`max_price`,`name`, `price`) VALUES ('Pasemka, ombre',1,160,'Pasemka, ombre',110);
INSERT INTO `SalonikBella`.`haircut` (`description`,`gender`,`max_price`,`name`, `price`) VALUES ('Fryzury okolicznościowe',1,130,'Fryzury okolicznościowe',40);
INSERT INTO `SalonikBella`.`haircut` (`description`,`gender`,`max_price`,`name`, `price`) VALUES ('Styling (trwała)',1,0,'Styling (trwała)',100);
INSERT INTO `SalonikBella`.`haircut` (`description`,`gender`,`max_price`,`name`, `price`) VALUES ('Keratynowe prostowanie włosów',1,350,'Keratynowe prostowanie włosów',250);
INSERT INTO `SalonikBella`.`haircut` (`description`,`gender`,`max_price`,`name`, `price`) VALUES ('Nawilżanie włosów ',1,0,'Nawilżanie włosów ',60);

/* perfumy 15 ml */
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Eksplozja nut cytrusowych tworzy bardzo pociągający zapach. Delikatne akordy piżma napawają  pogodnym nastawieniem.','BRAK','m','beach','img/perfumy/beach/beach15.jpg',25,'Aromatyczno - Drzewna, Beach to zrównoważony, czysty zapach. Idealny dla kobiet i mężczyzn. Nuty głowy: Pomarańcza, nuty serca: Konwalia, nuty bazy: Piżmo.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Fuzja nut hesperydowych z cyklamenem i nutami drzewnymi pozwoliła na stworzenie ekspresywnego zapachu pachnącego wolnością.','BRAK','m','acqua per uomo','img/perfumy/acqua-per-uomo/acqua-per-uomo15.jpg',25,'Aromatyczno - Wodna. Acqua per uomo to świeży zapach dla naturalnego i współczesnego mężczyzny. Nuty głowy: Bergamotka, nuty serca  Cyklamen, nuty bazy: Drzewo.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Te perfumy pełne aromatycznych nut nadają mężczyźnie, który ich używa uwodzicielskiego i prawdziwie męskiego charakteru.','BRAK','m','WOW SCENT!','img/perfumy/wow-scent!/wow-scent!15.jpg',25,'Paprociowo – Korzenny. Wow Scent! to męskie perfumy dla żywiołowego I radosnego mężczyzny. Nuty głowy: Mięta, nuty serca: Szałwia, nuty bazy: Wanilia','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Uwodzicielska i intensywna kompozycja zapachowa będąca połączeniem pogodnej maliny z miękką gardenią i ciepłem paczuli.','BRAK','k','power woman','img/perfumy/power-woman/power-woman15.jpg',25,'Kwiatowo - drzewna.Power Woman to zapach pełen oryginalnych kontrastów. Dla ambitnej kobiety z charakterem. Nuty głowy: Malina, nuty serca: Gardenia, nuty bazy: Paczuli.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Odczuwalna w nucie głowy świeżość mandarynki w połączeniu z kwiatowymi i korzennymi esencjami gardenii i drzewa sandałowego tworzy wyjątkowo wyrafinowany zapach.','BRAK','k','notion woman','img/perfumy/notion-woman/notion-woman15.jpg',25,'Kwiatowo - Owocowa. Notion Woman to zapach dla wesołej, dynamicznej kobiety, emanującej optymizmem i elegancją. Nuty głowy: Mandarynka, nuty serca: Gardenia, nuty bazy: Sandał.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Mocno pudrowy aromat białych kwiatów, orientalne tło i ciepło kwiatowego bukietu odzwierciedlają zmysłowość i delikatność. ','BRAK','k','VELFASHION','img/perfumy/velfashion/velfashion15.jpg',25,'Orientalno - Waniliowa. Velfashion  to złożony i elegancki zapach. Dla kobiety z wdziękiem i charyzmą. Nuty głowy: Bergamotka, nuty serca: Jaśmin, nuty bazy: Wetiweria pachnąca.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Uwodzicielska fuzja cytryny, imbiru i kardamonu daje w efekcie pocigąjący i niezapomniany zapach','BRAK','m','west','img/perfumy/west/west15.jpg',25,'Szyprowo-Drzewna. West to perfumy dla odważnego i charyzmatycznego mężczyzny. Nuty głowy: Cytryna, nuty serca: Kardamon, nuty bazy: Bób tonka','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Silne nuty bergamotki i lawendy nadają kompozycji klasyczny męski charakter, które łagodzi delikatny aromat ambry.','BRAK','m','CARIBBEAN','img/perfumy/caribbean/caribbean15.jpg',25,'Paprociowo - Ambrowa. Caribbean jest to świeży zapach dla prawdziwego i przebojowego mężczyzny. Nuty głowy: Bergamotka, nuty serca: Lavenda, nuty bazy: Bursztyn','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Charakterystyczna piramida zapachowa, w której dominują nuty orientalne, tworzy zapach emanujący siłą i trwałością.','BRAK','m','INSTINT','img/perfumy/instint/instint15.jpg',25,'Orientalno - Korzenna. Instint to zapach wyjątkowo prowokacyjny. Dla odważnego i seksownego mężczyzny. Nuty głowy: Kwiat pomarńczy, nuty serca: Lavenda, nuty bazy: Wanilia.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Orzeźwiający i zmysłowy zapach wykreowany dzięki połączeniu energicznych i intensywnych nut drzewnych ze słodyczą jaśminu.','BRAK','m','platinum','img/perfumy/platinum/platinum15.jpg',25,'Drzewno - wodna. Platinum  to zapach pełen mocy. Dla aktywnego, uwielbiającego przygody mężczyzny. Nuty głowy: Grejpfrut, nuty serca: Jaśmin, nuty bazy: Drzewo.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Owocowe nuty głowy ustępują ciepłym nutom drzewnym kreując wyrafinowany i elegancki zapach.','BRAK','m','MOMENT','img/perfumy/moment/moment15.jpg',25,'Orientalno - drzewna. Moment to elegancki, czysty zapach. Dla mężczyzny pewnego siebie. Nuty głowy: Jabłko, nuty serca: Cynamon, nuty bazy: Drzewo.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Nowoczesne połączenie swieżych i iskrzących akordów zapewniają temu zapachowi zmysłowość, wyrazistość i osobowość.','BRAK','m','metal sport','img/perfumy/metal-sport/metal-sport15.jpg',25,'Szyprowo - Owocowa. Metal Sport to zapach dla atrakcyjnego, uwodzicielskiego i energicznego mężczyzny. Nuty głowy: Mandarynka, nuty serca: Drzewo, nuty bazy: Wetiweria pachnąca.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Otulający aromat piżma i elegancja białej róży kształtuje perfumy o namiętnej zmysłowości.','BRAK','k','nicolas white','img/perfumy/nicolas-white/nicolas-white15.jpg',25,'Kwiatowo-Drzewna. Nicolás White jest to piżmowo- kwiatowy zapach dla bardzo zmysłowej kobiety. Nuty głowy: Biała róża, nuty serca : Piżmo, nuty bazy: Biały cedr.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Owocowe i aksamitne nuty granatu, wraz z  czarującą wonią orchidei i fiołka, tworzą odważny i wykwintny zapach.','BRAK','k','aroma','img/perfumy/aroma/aroma15.jpg',25,'Orientalno - Kwiatowa. Aroma to  egzotyczny i nadający blask zapach. Dla eleganckiej i tajemniczej kobiety. Nuty głowy: Granat, nuty serca: Orchidea, nuty bazy: Fiołek.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Nowoczesna kompozycja aromatyczna tworzy odważny zapach, odzwierciedlający luksus i elegancję.','BRAK','k','cheante','img/perfumy/cheante/cheante15.jpg',25,'Szyprowo - Kwiatowa. Cheante to  kobiecy i zmysłowy zapach. Dla eleganckiej i szykownej kobiety. Nuty głowy: Bergamotka, nuty serca: Róża, nuty bazy: Piżmo.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Współczesna i luksusowa kompozycja zapachowa powstała z połączenia wibrujących nut głowy z namiętną fuzją  jaśminu i wetywerii.','BRAK','k','SOPHISTICATE','img/perfumy/sophiesticate/sophiesticate15.jpg',25,'Orientalno - Kwiatowa. Sophisticate to zmysłowy zapach. Dla namiętnej i silnej kobiety. Nuty głowy: Liczi, nuty serca: Jaśmin, nuty bazy: Wetiweria pachnąca.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Pociągające słodkie nuty czarnej porzeczki i silna obecność wanilii sprawiają, iż od samego początku perfumy posiadają własną osobowość.','BRAK','k','adriana','img/perfumy/adriana/adriana15.jpg',25,'Szyprowo - Owocowa. Pociągające słodkie nuty czarnej porzeczki i silna obecność wanilii sprawiają, iż od samego początku perfumy posiadają własną osobowość. Nuty głowy: Czarna porzeczka,nuty serca: Wanilia, nuty bazy: Drzewo.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Świeżość bergamotki i elegancja róży z dodatkiem waniliowej głębi tych perfum, nadają im ponadczasowy i nowoczesny charakter.','BRAK','k','ADRIANA ROSE','img/perfumy/adriana-rose/adriana-rose15.jpg',25,'Chypre Fruity. Jest to elegancki i niepowtarzalnie kobiecy zapach. Nuty głowy: Bergamotka, nuty serca: Róża, nuty bazy: Wanilia.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Świeżość grejpfruta, delikatność jaśminu oraz poetyckie połączenie ambry tworzy perfumy słodkie i cytrusowe.','BRAK','k','for you','img/perfumy/for-you/for-you15.jpg',25,'Kwiatowo-Owocowy. For You są to subtelne i delikatne perfumy dla optymistycznej kobiety. Nuty głowy: Bergamotka, Grejpfrut, nuty serca: Jaśmin, nuty bazy: Bursztyn, Biały cedr.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Zmysłowy zapach będący połączeniem delikatnego jabłka i bambusu, które nadają świeżych akrodów nutą drzewnym.','BRAK','k','kara','img/perfumy/kara/kara15.jpg',25,'Kwiatowo - Owocowa. Kara to pobudzający zapach. Dla radosnej, cieszącej się życiem kobiety. Nuty głowy: Jabłko, nuty serca: Bambus, nuty bazy: Piżmo.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Intensywne połączenie białych kwiatów i bobu tonka tworzy odważne i wyszukane perfumy.','BRAK','k','very special','img/perfumy/very-special/very-special15.jpg',25,'Orientalno - Kwiatowa. Very Special to perfumy dla wpływowej i namiętnej kobiety. Nuty głowy: Tuberoza, Migdały, nuty serca: Jaśmin, nuty bazy: Bób tonka.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Zapach otulony miękkością i czułością dzięki harmonijnemu połączeniu nut zapachowych. Jego pudrowe nuty upajają marzeniami.','BRAK','k','SEDUCCIÓN','img/perfumy/seduccion/seduccion15.jpg',25,'Kwiatowo - Kwiatowa. Seducción to słodki, ujmujący zapach. Dla wyjątkowej i delikatnej kobiety. Nuty głowy: Piwonia, nuty serca: Konwalia, nuty bazy: Piżmo.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Kwiatowa etuida wraz z nutami wanilii tworzy niezapomniany zapach pudrowy. Delikatny a zarazem silny i wyjątkowy aromat rozbudza niezliczone doznania.','BRAK','k','berlue','img/perfumy/berlue/berlue15.jpg',25,'Kwiatowo - Aldehydowa. Berlue to  ponadczasowy zapach. Dla kobiety uwielbiającej klasyczny i elegancki styl. Nuty głowy: Kwiat pomarńczy, nuty serca: Róża, nuty bazy: Wanilia.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Dominujący zapach wanilii sprawia, że zapach ten jest urzekający i charyzmatyczny. ','BRAK','k','temis','img/perfumy/temis/temis15.jpg',25,'Orientalno - Kwiatowa. Temis to perfumy dla kobiety tajemniczej i prowokującej. Nuty głowy: Kwiat Imbiru, nuty serca: Jaśmin Wodny, nuty bazy: Wanilia.','15');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Zapach elegancki i zmysłowy, powstały z kreatywnego połączenia nut cytrusowych z cynamonem i świeżą paczulą.','BRAK','m','power','img/perfumy/power/power15.jpg',25,'Power to intesywny, pobudzający zapach. Dla uwodzicielskiego, tajemniczego mężczyzny. Nuty głowy: Grejpfrut, nuty serca: Cynamon, nuty bazy: Paczuli.','15');

/* perfumy 50 ml */
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Zapach elegancki i zmysłowy, powstały z kreatywnego połączenia nut cytrusowych z cynamonem i świeżą paczulą.','BRAK','m','power','img/perfumy/power/power50.jpg',999,'Power to intesywny, pobudzający zapach. Dla uwodzicielskiego, tajemniczego mężczyzny. Nuty głowy: Grejpfrut, nuty serca: Cynamon, nuty bazy: Paczuli.','50');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Żywe cytrusowe nuty harmonijnie otaczają spokojny aromat róży, nadając życiu radosny i delikatny zapach.','BRAK','k','vivacity','img/perfumy/vivacity/vivacity50.jpg',999,'Vivacity  to zapach dla żywiołowej i słodkiej kobiety. Nuty głowy: Mandarynka, nuty serca: Róża Grasse, nuty bazy: Drzewo sandałowe.','50');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Połączenie bergamotki i imbiru pozwala poczuć silną świeżość. Świeżość kontrastuje z zapachem jabłka, a nuty szałwii i jałowca wraz z lawendą gwarantują zapach silnej męskości.','BRAK','m','resolu','img/perfumy/resolu/resolu50.jpg',999,'Reslou dla energicznego i wytrwałego mężczyzny. Nuty głowy: Bergamotka, Jabłko, Imbir, nuty serca: Jałowieć, Lawenda, Szałwia , nuty bazy: Drewno bursztynowe, Olibanum, Fasolka tonka.','50');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Intensywność bergamotki w połączeniu z naturalną dzikością skóry i intensywnością kakao sprawiają, że te perfumy są niezapomnianym przeżyciem, które sprawi, że przemierzysz cały świat.','BRAK','m','peak','img/perfumy/peak/peak50.jpg',999,'Peak dla mężczyzny pełnego życia z charakterem. Nuty głowy: Bergamotka, nuty serca: Skóra, nuty bazy: Kakao.','50');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Cytrusowy dotyk bergamotki wraz z urzekającymi nutami tuberozy i paczuli tworzą intensywny i kobiecy zapach.','BRAK','k','tendenze','img/perfumy/tendenze/tendenze50.jpg',999,'Tendenze to mocny cytrusowo kwiatowy zapach. Idealny dla eleganckiej i odważnej kobiety. Nuty głowy: Bergamotka, nuty serca: Tuberoza, nuty bazy: Paczula.','50');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Zmysłowość nut zapachowych, które tworzą te perfumy sprawia, że kobieta, która ich używa jest namiętna i nie można się jej oprzeć.','BRAK','k','suerte','img/perfumy/suerte/suerte50.jpg',999,'Suerte to  zapach dla uwodzicielskiej i uroczej kobiety. Nuty głowy: Ylang-ylang, nuty serca: Wanilia, nuty bazy: Białe Piżmo.','50');

/* perfumy 100 ml */
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Owocowe i aksamitne nuty granatu, wraz z  czarującą wonią orchidei i fiołka, tworzą odważny i wykwintny zapach.','BRAK','k','aroma','img/perfumy/aroma/aroma100.jpg',999,'Orientalno - Kwiatowa. Aroma to  egzotyczny i nadający blask zapach. Dla eleganckiej i tajemniczej kobiety. Nuty głowy: Granat, nuty serca: Orchidea, nuty bazy: Fiołek.','100');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Odczuwalna w nucie głowy świeżość mandarynki w połączeniu z kwiatowymi i korzennymi esencjami gardenii i drzewa sandałowego tworzy wyjątkowo wyrafinowany zapach.','BRAK','k','notion woman','img/perfumy/notion-woman/notion-woman100.jpg',999,'Kwiatowo - Owocowa. Notion Woman to zapach dla wesołej, dynamicznej kobiety, emanującej optymizmem i elegancją. Nuty głowy: Mandarynka, nuty serca: Gardenia, nuty bazy: Sandał.','100');
INSERT INTO `SalonikBella`.`perfume` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`smell`,`volume`) VALUES ('Uwodzicielska i intensywna kompozycja zapachowa będąca połączeniem pogodnej maliny z miękką gardenią i ciepłem paczuli.','BRAK','k','power woman','img/perfumy/power-woman/power-woman100.jpg',999,'Kwiatowo - drzewna.Power Woman to zapach pełen oryginalnych kontrastów. Dla ambitnej kobiety z charakterem. Nuty głowy: Malina, nuty serca: Gardenia, nuty bazy: Paczuli.','100');

/* pictures */
INSERT INTO `SalonikBella`.`picture` (`description`,`name`,`path`,`title`) VALUES ('','','img/galeria/picture1.jpg','');
INSERT INTO `SalonikBella`.`picture` (`description`,`name`,`path`,`title`) VALUES ('','','img/galeria/picture2.jpg','');
INSERT INTO `SalonikBella`.`picture` (`description`,`name`,`path`,`title`) VALUES ('','','img/galeria/picture3.jpg','');
INSERT INTO `SalonikBella`.`picture` (`description`,`name`,`path`,`title`) VALUES ('','','img/galeria/picture4.jpg','');
/* INSERT INTO `SalonikBella`.`picture` (`description`,`name`,`path`,`title`) VALUES ('','','','');*/

/* products */
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`,`category_id`) VALUES ('Szampon do włosów sychych i zniszczonych',' Posiada ekscytujący zapach aromatycznego kokosa.','k','Szampon kokosowy','img/produkty/category/kreatyna.png',15.99,'Joanna','1000ml',1);
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`,`category_id`) VALUES ('Szampon do włosów sychych i zniszczonych',' Posiada ekscytujący zapach aromatycznego kokosa.','k','Szampon kokosowy','img/produkty/category/kreatyna.png',15.99,'Joanna','1000ml',1);
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`,`category_id`) VALUES ('Szampon do włosów sychych i zniszczonych',' Posiada ekscytujący zapach aromatycznego kokosa.','k','Szampon kokosowy','img/produkty/category/kreatyna.png',15.99,'Joanna','1000ml',1);
INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`,`category_id`) VALUES ('Szampon do włosów sychych i zniszczonych',' Posiada ekscytujący zapach aromatycznego kokosa.','k','Szampon kokosowy','img/produkty/category/kreatyna.png',15.99,'Joanna','1000ml',2);
/* INSERT INTO `SalonikBella`.`product` (`description`,`extra_info`,`gender`,`name`,`photo`,`price`,`producer`,`volume`,`category_id`) VALUES ('','','','','',,'','',''); */

/* category */
INSERT INTO `SalonikBella`.`category` (`description`,`name`,`photo`) VALUE ('Szampony do włosów','szampon','img/produkty/category/szampony.png');
INSERT INTO `SalonikBella`.`category` (`description`,`name`,`photo`) VALUE ('Kosmetyki do stylizacji włosów','stylizacja','img/produkty/category/stylizacja.png');
INSERT INTO `SalonikBella`.`category` (`description`,`name`,`photo`) VALUE ('Serum do włosów','serum','img/produkty/category/serum.png');
INSERT INTO `SalonikBella`.`category` (`description`,`name`,`photo`) VALUE ('Kuracje do włosów','kuracje','img/produkty/category/kuracje.png');
INSERT INTO `SalonikBella`.`category` (`description`,`name`,`photo`) VALUE ('Odżywki i maski do włosów','odzywki-maski','img/produkty/category/odzywki-maski.png');
INSERT INTO `SalonikBella`.`category` (`description`,`name`,`photo`) VALUE ('Farby do włosów','farby','img/produkty/category/farby.png');
INSERT INTO `SalonikBella`.`category` (`description`,`name`,`photo`) VALUE ('Produkty do kreatynowego prostowania','kreatyna','img/produkty/category/kreatyna.png');

























